services:
  
  yawshop:
    image: yawshop:latest
    container_name: yawshop
    networks:
      - kludatabase
    ports:
      - "10.0.0.4:5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    
networks:
  kludatabase:
    external: true