services:
  
  yawshop:
    image: yawshop:latest
    container_name: yawshop
    networks:
      - kludatabase
    env_file:
      - .env
    restart: unless-stopped
    
networks:
  kludatabase:
    external: true